package com.callbackdev.chiaro.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// GENERATED by tools/gen_scheme.py from the source colors of DESIGN.md §2.2.
// Do not hand-edit: change a source there, regenerate, and let PaletteContrastTest
// say whether the result still holds. This scheme is only ever used when dynamic
// color is off or unavailable (ChiaroTheme decides); it is the app looking like
// itself rather than like the wallpaper.

internal val ChiaroLightScheme: ColorScheme = lightColorScheme(
    primary = Color(0xFF835400),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDDB7),
    onPrimaryContainer = Color(0xFF281900),
    inversePrimary = Color(0xFFFFB958),
    secondary = Color(0xFF18648C),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFC9E6FF),
    onSecondaryContainer = Color(0xFF001E2F),
    tertiary = Color(0xFF675687),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFEADDFF),
    onTertiaryContainer = Color(0xFF1F143D),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEDBD3),
    onErrorContainer = Color(0xFF3B0A00),
    background = Color(0xFFFCF9F3),
    onBackground = Color(0xFF1E1B17),
    surface = Color(0xFFFCF9F3),
    onSurface = Color(0xFF1E1B17),
    surfaceVariant = Color(0xFFE7E2D5),
    onSurfaceVariant = Color(0xFF4A463C),
    surfaceTint = Color(0xFF835400),
    inverseSurface = Color(0xFF33302C),
    inverseOnSurface = Color(0xFFF4F0EB),
    outline = Color(0xFF7B776B),
    outlineVariant = Color(0xFFCBC6B9),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFCF9F3),
    surfaceDim = Color(0xFFDDD9D4),
    surfaceContainer = Color(0xFFF1EDE8),
    surfaceContainerHigh = Color(0xFFEBE8E2),
    surfaceContainerHighest = Color(0xFFE5E2DD),
    surfaceContainerLow = Color(0xFFF7F3EE),
    surfaceContainerLowest = Color(0xFFFFFFFF)
)

internal val ChiaroDarkScheme: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB958),
    onPrimary = Color(0xFF452B00),
    primaryContainer = Color(0xFF643F00),
    onPrimaryContainer = Color(0xFFFFDDB7),
    inversePrimary = Color(0xFF835400),
    secondary = Color(0xFF91CDFA),
    onSecondary = Color(0xFF00344D),
    secondaryContainer = Color(0xFF014C6D),
    onSecondaryContainer = Color(0xFFC9E6FF),
    tertiary = Color(0xFFD2BDF4),
    onTertiary = Color(0xFF362855),
    tertiaryContainer = Color(0xFF4E3F6D),
    onTertiaryContainer = Color(0xFFEADDFF),
    error = Color(0xFFFEB4A6),
    onError = Color(0xFF6A0000),
    errorContainer = Color(0xFF94000C),
    onErrorContainer = Color(0xFFFEDBD3),
    background = Color(0xFF16130E),
    onBackground = Color(0xFFE5E2DD),
    surface = Color(0xFF16130E),
    onSurface = Color(0xFFE5E2DD),
    surfaceVariant = Color(0xFF4A463C),
    onSurfaceVariant = Color(0xFFCBC6B9),
    surfaceTint = Color(0xFFFFB958),
    inverseSurface = Color(0xFFE5E2DD),
    inverseOnSurface = Color(0xFF33302C),
    outline = Color(0xFF959084),
    outlineVariant = Color(0xFF4A463C),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3B3935),
    surfaceDim = Color(0xFF16130E),
    surfaceContainer = Color(0xFF221F1B),
    surfaceContainerHigh = Color(0xFF2C2A26),
    surfaceContainerHighest = Color(0xFF373430),
    surfaceContainerLow = Color(0xFF1E1B17),
    surfaceContainerLowest = Color(0xFF110E07)
)
